services:
  img:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm/v7
#        - linux/amd64
#        - linux/arm64
      tags:
        - amneziawg-mikrotik:latest

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

# How to prepare image:
#
# docker compose build
# docker save amneziawg-mikrotik:latest > amneziawg-mikrotik.tar
#
# scp amneziawg-mikrotik.tar <router-ip>:
